nasm -f bin Source/art.asm -o Art.img
nasm -f bin Source/aurora.asm -o Aurora.img
nasm -f bin Source/formule.asm -o Formule.img
nasm -f bin Source/julia.asm -o Julia.img
nasm -f bin Source/plasma.asm -o Plasma.img
nasm -f bin Source/sierspinki2.asm -o Sierspinki2.img
nasm -f bin Source/sierspinski.asm -o Sierspinski.img
nasm -f bin Source/static.asm -o Static.img
nasm -f bin Source/xor.asm -o Xor.img
nasm -f bin Source/null.asm -o NullRoto.img
